import { LotteryConfig } from "./types";

export const LOTTERY_CONFIGS: Record<string, LotteryConfig> = {
  megasena: {
    id: "megasena",
    name: "megasena",
    displayName: "Mega-Sena",
    apiEndpoint: "megasena",
    color: "#209869",
    colorLight: "#209869/15",
    numberRange: { min: 1, max: 60 },
    drawCount: 6,
    betMin: 6,
    betMax: 20,
    minMatchForPrize: 4,
  },
  lotofacil: {
    id: "lotofacil",
    name: "lotofacil",
    displayName: "Lotofácil",
    apiEndpoint: "lotofacil",
    color: "#930089",
    colorLight: "#930089/15",
    numberRange: { min: 1, max: 25 },
    drawCount: 15,
    betMin: 15,
    betMax: 20,
    minMatchForPrize: 11,
  },
  quina: {
    id: "quina",
    name: "quina",
    displayName: "Quina",
    apiEndpoint: "quina",
    color: "#260085",
    colorLight: "#260085/15",
    numberRange: { min: 1, max: 80 },
    drawCount: 5,
    betMin: 5,
    betMax: 15,
    minMatchForPrize: 2,
  },
  lotomania: {
    id: "lotomania",
    name: "lotomania",
    displayName: "Lotomania",
    apiEndpoint: "lotomania",
    color: "#F78100",
    colorLight: "#F78100/15",
    numberRange: { min: 0, max: 99 },
    drawCount: 20,
    betMin: 50,
    betMax: 50,
    minMatchForPrize: 0,
    fixedBet: true,
    zeroBased: true,
  },
  timemania: {
    id: "timemania",
    name: "timemania",
    displayName: "Timemania",
    apiEndpoint: "timemania",
    color: "#00FF48",
    colorLight: "#00FF48/15",
    numberRange: { min: 1, max: 80 },
    drawCount: 7,
    betMin: 10,
    betMax: 10,
    minMatchForPrize: 3,
    fixedBet: true,
  },
  duplasena: {
    id: "duplasena",
    name: "duplasena",
    displayName: "Dupla Sena",
    apiEndpoint: "duplasena",
    color: "#A61324",
    colorLight: "#A61324/15",
    numberRange: { min: 1, max: 50 },
    drawCount: 6,
    betMin: 6,
    betMax: 15,
    minMatchForPrize: 3,
    hasSecondDraw: true,
  },
  diadesorte: {
    id: "diadesorte",
    name: "diadesorte",
    displayName: "Dia de Sorte",
    apiEndpoint: "diadesorte",
    color: "#CB7B18",
    colorLight: "#CB7B18/15",
    numberRange: { min: 1, max: 31 },
    drawCount: 7,
    betMin: 7,
    betMax: 15,
    minMatchForPrize: 4,
  },
  supersete: {
    id: "supersete",
    name: "supersete",
    displayName: "Super Sete",
    apiEndpoint: "supersete",
    color: "#A8CF45",
    colorLight: "#A8CF45/15",
    numberRange: { min: 0, max: 9 },
    drawCount: 7,
    betMin: 7,
    betMax: 21,
    minMatchForPrize: 3,
    isColumnBased: true,
    columns: 7,
    numbersPerColumn: 3,
    zeroBased: true,
  },
  maismilionaria: {
    id: "maismilionaria",
    name: "maismilionaria",
    displayName: "+Milionária",
    apiEndpoint: "maismilionaria",
    color: "#2D4AA3",
    colorLight: "#2D4AA3/15",
    numberRange: { min: 1, max: 50 },
    drawCount: 6,
    betMin: 6,
    betMax: 12,
    minMatchForPrize: 2,
    hasTrevos: true,
    trevoRange: { min: 1, max: 6 },
    trevoDrawCount: 2,
    trevoBetMin: 2,
    trevoBetMax: 6,
  },
};

export const LOTTERY_LIST = Object.values(LOTTERY_CONFIGS);

export function getLotteryConfig(id: string): LotteryConfig | undefined {
  return LOTTERY_CONFIGS[id];
}

export const MONTHS_PT = [
  "Janeiro",
  "Fevereiro",
  "Março",
  "Abril",
  "Maio",
  "Junho",
  "Julho",
  "Agosto",
  "Setembro",
  "Outubro",
  "Novembro",
  "Dezembro",
];
